### ISSUE TITLE
Logical problem in PaymentVerification

### ISSUE THREAD

**Issue by MCSH** [siamak/zarinpal-express-checkout#1]
Hi,

There is a couple of logical problems in payment verification. 

First of all, the callback url should be set to HOST/PaymentVerification.
Also based on Zarinpal's documentations, /PaymentVerification gets two values, Status and Authority.

Last the status must be 100, (currently it is anything but -21) for a successful order.

**Comment by siamak** [comment]
@MCSH Fixed. https://github.com/siamak/zarinpal-express-checkout/commit/3942159d9180d2861fba9187cde3d1969ad44b9d

**Comment by MCSH** [comment]
This doesn't fix the issues...

**Comment by siamak** [comment]
@MCSH Can you send a message to _@siamak_ (http://telegram.me/siamak) in telegram for this issue?
