### ISSUE TITLE
PaymentRequest does not send any request

### ISSUE THREAD

**Issue by hosein-xz** [siamak/zarinpal-express-checkout#2]
i'm using adonis and when i use ZarinpalCheckout.create and it return true value but after that when i'm trying to get PaymentRequest it does not send any thing and rest of my code running:
here is the code :

`var zarinpal = await ZarinpalCheckout.create('00000000-0000-0000-0000-000000000000', false);
            await zarinpal.PaymentRequest({
                Amount: order.total_price, // In Tomans
                CallbackURL: call_back_url,
                Description: '',
                // Email: 'hi@siamak.work',
                // Mobile: user.username
            }).then(response_zarinpal => {
                console.log(response_zarinpal);
                if (response_zarinpal.status == 100) {
                    response.redirect(response_zarinpal.url);
                }
            }).catch(err => {
                return response.json('failure');
            });

 return response.json('test');`

and it just show 'test'

**Comment by siamak** [comment]
`ZarinpalCheckout.create` create an instance. You don't use `await` before `ZarinpalCheckout.create` (It's not a promise!)
